### ISSUE TITLE
Missing './user_model/data/train.csv'

### ISSUE THREAD

**Issue by OLDSPICECODE** [HKUSTDial/HAIChart#12]
Where can I find or download the file: train.csv? I get this error when I want to run haichart.py
```
Traceback (most recent call last):
  File "haichart.py", line 11, in <module>
    from mcgs import MCGS, Node
  File "C:\Users\USER\Desktop\PFC\PFC1-3\Haichart\HAIChart\mcgs.py", line 18, in <module>
    from user_model.test_env_model import get_config_score
  File "C:\Users\USER\Desktop\PFC\PFC1-3\Haichart\HAIChart\user_model\test_env_model.py", line 31, in <module>
    data = load_data(FLAGS.data_dir, FLAGS.data_name)
  File "C:\Users\USER\Desktop\PFC\PFC1-3\Haichart\HAIChart\user_model\utils.py", line 45, in load_data
    with open("%s/%s" % (path, fname), "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: './user_model/data/train.csv'
```

**Comment by xypkent** [comment]
Hi,

Thank you for your message. The user_model module in HAIChart is based on IRecGAN, and the dataset used is from the paper Personalized Visualization Recommendation. You can find the dataset at the following link: https://networkrepository.com/personalized-vis-rec.

Please feel free to refer to this link for more information on the data.
